/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-white": "#FFFFFF",
        "surface-container-low": "#f2f4f7",
        "surface-bright": "#f7f9fc",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#d4e4fa",
        "surface-dim": "#d8dadd",
        "surface-tint": "#4d5f7d",
        "primary-fixed-dim": "#b5c7ea",
        "on-tertiary-container": "#79889c",
        "surface-container-high": "#e6e8eb",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#80d5cb",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#112030",
        "on-tertiary-fixed-variant": "#39485a",
        "secondary": "#0F766E",
        "on-primary-container": "#7587a7",
        "secondary-fixed": "#9cf2e8",
        "primary": "#0B1F3A",
        "primary-container": "#112030",
        "on-secondary-fixed-variant": "#00504a",
        "inverse-on-surface": "#eff1f4",
        "on-primary-fixed": "#071c36",
        "on-tertiary-fixed": "#0d1c2d",
        "surface-container": "#eceef1",
        "secondary-container": "#ccfbf1",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e6",
        "text-slate": "#1F2937",
        "on-secondary-fixed": "#00201d",
        "error": "#ba1a1a",
        "warning-amber": "#B45309",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#364764",
        "on-secondary-container": "#006f67",
        "surface-variant": "#e0e3e6",
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "error-red": "#B91C1C",
        "inverse-primary": "#b5c7ea",
        "tertiary": "#000712",
        "primary-fixed": "#d6e3ff",
        "outline": "#75777e",
        "tertiary-fixed-dim": "#b9c8de",
        "surface": "#f7f9fc",
        "outline-variant": "#c4c6ce",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#44474d",
        "error-container": "#ffdad6",
        "background": "#f7f9fc",
        "ui-steel": "#94A3B8",
        "accent-teal": "#0F766E",
        "primary-navy": "#0B1F3A",
        // preserve current fallback
        primary_fallback: {
          DEFAULT: '#0B1F3A',
          container: '#112030',
        },
        secondary_fallback: {
          DEFAULT: '#0F766E',
          container: '#ccfbf1',
        },
      },
      spacing: {
        "container-max": "1200px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "base": "8px",
        "section-gap": "80px"
      },
      fontFamily: {
        sans: [
          'var(--font-inter)',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "caption": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-xl": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "caption": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
